freebsd_task:
    install_script:
    - ASSUME_ALWAYS_YES=yes pkg bootstrap -f && pkg install -y cmocka cmake ninja
    build_script:
    - mkdir build
    - cd build
    - cmake -GNinja -DWITH_TESTS=ON
      -DCBOR_CUSTOM_ALLOC=ON
      -DCMAKE_BUILD_TYPE=Debug
      -DSANITIZE=OFF
      ..
    - ninja -j $(sysctl -n hw.ncpu)
    test_script:
    - cd build
    - ctest -VV
    matrix:
    - name: freebsd12-4-amd64
      freebsd_instance:
        image: freebsd-12-4-release-amd64
    - name: freebsd13-2-amd64
      freebsd_instance:
        image: freebsd-13-2-release-amd64
